apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube2iam
  namespace: default # change to suit your context
  labels:
    app: kube2iam
spec:
  selector:
    matchLabels:
      name: kube2iam
  template:
    metadata:
      labels:
        name: kube2iam
    spec:
      hostNetwork: true
      containers:
        - name: kube2iam
          image: jtblin/kube2iam:latest
          args:
            - "--app-port=8282"
            - "--metrics-port=8282"
            - "--host-interface=cali+"
            #- "--host-ip=$(KUBERNETES_SERVICE_HOST)"
            - "--host-ip=$(HOST_IP)"
            - "--node=$(NODE_NAME)"
            - "--iptables=true"
            - "--auto-discover-base-arn"
            - "--auto-discover-default-role"
            - "--log-level=debug"
            - "--verbose"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: AWS_REGION
              value: "us-west-2"
          ports:
            - containerPort: 8282 # port 8080/8181 are usually taken/bound already
              hostPort: 8282
              name: http
          securityContext:
            privileged: true
      serviceAccount: default # change to suit your context
      serviceAccountName: default # change to suit your context
---

